
"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import type { Student, Semester } from "@/data/mock-data";

interface MarksheetDialogProps {
  student: Student | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const SemesterTable = ({ semester }: { semester: Semester }) => (
  <div className="mb-6">
    <h4 className="font-semibold text-lg mb-2">Semester {semester.semester} - GPA: <span className="text-primary">{semester.gpa?.toFixed(2)}</span></h4>
    <div className="border rounded-md">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Course Code</TableHead>
            <TableHead>Course Name</TableHead>
            <TableHead className="text-center">Credits</TableHead>
            <TableHead className="text-center">Marks</TableHead>
            <TableHead className="text-center">Grade</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {semester.subjects.map((subject, index) => (
            <TableRow key={index}>
              <TableCell>{subject.courseCode}</TableCell>
              <TableCell>{subject.courseName}</TableCell>
              <TableCell className="text-center">{subject.credits}</TableCell>
              <TableCell className="text-center">{subject.marks}</TableCell>
              <TableCell className="text-center">
                <Badge variant={subject.gradePoint === 0 ? 'destructive' : 'outline'}>
                    {subject.grade}
                </Badge>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  </div>
);

export default function MarksheetDialog({ student, open, onOpenChange }: MarksheetDialogProps) {
  if (!student) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold text-primary">{student.name}</DialogTitle>
          <DialogDescription>
            Register Number: {student.regNo} | Final CGPA: <span className="font-bold text-foreground">{student.cgpa?.toFixed(2)}</span>
          </DialogDescription>
        </DialogHeader>
        <Separator />
        <ScrollArea className="h-[60vh] pr-4">
          {student.semesters.map((semester) => (
            <SemesterTable key={semester.semester} semester={semester} />
          ))}
        </ScrollArea>
        <Separator />
        <DialogFooter className="text-sm text-muted-foreground">
          This is a consolidated marksheet generated by the GPA Calculator.
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
